### ISSUE TITLE
SysPrefix looks strange

### ISSUE THREAD

**Issue by guettli** [jnmclarty/pyenvdiff-lib#15]
* PyEnvDiff version: pyenvdiff==0.2.0
* Python version: Python 2.7.15rc1
* Operating System: Ubuntu 18.04.1 LTS

### Description
I executed `python -m pyenvdiff.info my_environment.json `

the part of SysPrefix looks strange:

```

SysPrefix
*********
E
r
r
o
r
 
a
t
t
e
m
p
t
i
n
g
 
t
o
 
c
o
l
l
e
c
t
 
(
S
y
s
P
r
e
f
i
x
)
:
 
'
m
o
d
u
l
e
'
 
o
b
j
e
c
t
 
h
a
s
 
n
o
 
a
t
t
r
i
b
u
t
e
 
'
b
a
s
e
_
e
x
e
c
_
p
r
e
f
i
x
'
```

**Comment by jnmclarty** [comment]
Thanks so much for taking the time to report this issue!  I know exactly the problem, I will fix it this weekend and cut a new release.
